# Site wide configuration

title:            Blog pessoal
locale:           en_US
url:              //marcelomesmo.github.io


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Marcelo de Barros Barbosa
  avatar: foto-icone.png
  bio: |
    26. Desenvolvedor Groovy. Profº de Desenvolvimento de Jogos Digitais no IFRN.  
    Han atirou primeiro.
  email: marcelo.barbosa (at) ifrn (dot) edu (dot) br 
  disqus-shortname: marcelomesmo
  twitter: #username 
  facebook: mdbarrosb 
  google:
    plus: #username
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: marcelomesmo
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: mbbarbosa
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: attentionwho
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username

#comments: true
include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

theme: jekyll-theme-merlot